Lab3/Lab3EDI_1C18/Models/Partido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3EDI_1C18.Models
{
    public class Partido
    {
        public int noPartido { get; set; }
        public DateTime FechaPartido { get; set; }
        public string Grupo { get; set; }
        public string Pais1 { get; set; }
        public string Pais2 { get; set; }
        public string Estadio { get; set; }
    }
}

Lab3/Lab3EDI_1C18/Controllers/PartidoController.cs
using Lab3EDI_1C18.DBContext;
using Lab3EDI_1C18.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TDA.Clases;

namespace Lab3EDI_1C18.Controllers
{
    public class PartidoController : Controller
    {
        DefaultConnection db = DefaultConnection.getInstance;
        // GET: Partido
        public ActionResult Index()
        {
            return View(db.listaPartido.ToList());
        }

        public ActionResult Buscar(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaNoPartido.Find(x => x.noPartido == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        public ActionResult Buscar1(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaFechaPartido.Find(x => x.FechaPartido.ToString("MMddyyyy") == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }


        public ActionResult IndexPorFecha()
        {
            return View(db.listaFechaPartido.ToList());
        }

        public ActionResult IndexPorNumero()
        {
            return View(db.listaNoPartido.ToList());
        }

        // GET: Partido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Partido/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Partido/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "noPartido,FechaPartido,Grupo,Pais1,Pais2,Estadio")] Partido partido)
        {
            try
            {
                // TODO: Add insert logic here
                db.arbolFechaPartido.FuncionObtenerLlave = ObtenerFecha;
                db.arbolFechaPartido.FuncionCompararLlave = CompararFecha;
                db.arbolNoPartido.FuncionObtenerLlave = ObtenerNumero;
                db.arbolNoPartido.FuncionCompararLlave = CompararNumero;

                db.listaFechaPartido.Clear();
                db.listaNoPartido.Clear();

                db.arbolFechaPartido.Insertar(partido);
                db.arbolNoPartido.Insertar(partido);
                db.listaPartido.Add(partido);
                Escribir_archivoNum(partido);
                Escribir_archivoFecha(partido);
                if (db.arbolFechaPartido.hizoEquilibrio == true)
                {
                    EscribirEquilibrioFecha(partido);
                }

                if (db.arbolNoPartido.hizoEquilibrio == true)
                {
                    EscribirEquilibrioNum(partido);
                }
                db.arbolFechaPartido.EnOrden(RecorrerPartidoInFecha);
                db.arbolNoPartido.EnOrden(RecorrerPartidoInNumero);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public void EscribirEquilibrioNum(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualNum.txt", sobreescribir);
            sw.WriteLine("Se hizo equilibrio con el partido " + info.noPartido);
            sw.Close();
        }       
        public void Escribir_archivoNum(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualNum.txt", sobreescribir);
            sw.WriteLine("Se inserto el partido NO. " + info.noPartido);
            sw.Close();
        }
        public void Escribir_EliminararchivoNum(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualNum.txt", sobreescribir);
            sw.WriteLine("Se elimino el partido NO. " + info.noPartido);
            sw.Close();
        }
        public void EscribirEquilibrioFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualFecha.txt", sobreescribir);
            sw.WriteLine("Se hizo equilibrio con el partido " + info.noPartido);
            sw.Close();
        }
        public void Escribir_archivoFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualFecha.txt", sobreescribir);
            sw.WriteLine("Se inserto el partido NO. " + info.FechaPartido);
            sw.Close();
        }

        public void Escribir_EliminararchivoFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolManualFecha.txt", sobreescribir);
            sw.WriteLine("Se elimino el partido NO. " + info.FechaPartido);
            sw.Close();
        }



        // GET: Partido/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Partido/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaNoPartido.Find(x => x.noPartido == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        // POST: Partido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                Partido cg = db.listaFechaPartido.Find(x => x.noPartido == id);
                db.arbolNoPartido.Eliminar2(cg.noPartido);
                Escribir_EliminararchivoNum(cg);
                if (db.arbolNoPartido.hizoEquilibrio == true)
                {
                    EscribirEquilibrioNum(cg);
                }

                db.listaFechaPartido.Clear();
                
                db.arbolNoPartido.EnOrden(RecorrerPartidoInNumero);

                return RedirectToAction("IndexPorNumero");
            }
            catch
            {
                return View();
            }
        }

        [ValidateInput(false)]
        public ActionResult Delete1(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaFechaPartido.Find(x => x.FechaPartido.ToString("MMddyyyy") == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        // POST: CargaPartido/Delete/5
        [HttpPost, ValidateInput(false)]
        public ActionResult Delete1(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                Partido cg = db.listaFechaPartido.Find(x => x.FechaPartido.ToString("MMddyyyy") == id);
                db.arbolFechaPartido.Eliminar2(cg.FechaPartido);
                Escribir_EliminararchivoFecha(cg);
                if (db.arbolFechaPartido.hizoEquilibrio == true)
                {
                    EscribirEquilibrioFecha(cg);
                }

                db.listaFechaPartido.Clear();
                

                db.arbolFechaPartido.EnOrden(RecorrerPartidoInFecha);

                return RedirectToAction("IndexInFecha");
            }
            catch
            {
                return View();
            }
        }

        public void RecorrerPartidoInFecha(Nodo<Partido> actual)
        {
            db.listaFechaPartido.Add(actual.valor);
        }

        public void RecorrerPartidoInNumero(Nodo<Partido> actual)
        {
            db.listaNoPartido.Add(actual.valor);
        }

        public static int ObtenerNumero(Partido dato)
        {
            return dato.noPartido;
        }

        public static DateTime ObtenerFecha(Partido dato)
        {
            return dato.FechaPartido;
        }

        public static int CompararNumero(int actual, int nuevo)
        {
            return actual.CompareTo(nuevo);
        }

Lab3/Lab3EDI_1C18/Views/Partido/Buscar.cshtml
Buscar
@model Lab3EDI_1C18.Models.Partido
@{
    ViewBag.Title = "Buscar";
}

<h2>Partido buscado de la Copa Mundial de la FIFA Rusia 2018</h2>

<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>
    <br />
    @Html.ActionLink("Back to List", "IndexPorPartido")

Lab3/Lab3EDI_1C18/Views/Partido/Buscar1.cshtml
@model Lab3EDI_1C18.Models.Partido
@{
    ViewBag.Title = "BuscarFecha";
}

<h2>Partido buscado por fecha de la Copa Mundial de la FIFA Rusia 2018</h2>

<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>
    <br />
    @Html.ActionLink("Back to List", "IndexPorFecha")

Lab3/Lab3EDI_1C18/Views/Partido/Create.cshtml
@model Lab3EDI_1C18.Models.Partido

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.noPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.noPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab3/Lab3EDI_1C18/Views/Partido/Delete.cshtml
@model Lab3EDI_1C18.Models.Partido

@{
    ViewBag.Title = "Eliminar por numero";
}

<h2>Eliminar por numero de partido de la Copa Mundial de la FIFA Rusia 2018</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexPorNumero")
        </div>
    }
</div>

Lab3/Lab3EDI_1C18/Views/Partido/Delete1.cshtml
@model Lab3EDI_1C18.Models.Partido

@{
    ViewBag.Title = "Eliminar por fecha";
}

<h2>Eliminar por Fecha de la Copa Mundial de la FIFA Rusia 2018</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexInFecha")
        </div>
    }
</div>

Lab3/Lab3EDI_1C18/Views/Partido/Index.cshtml
@model IEnumerable<Lab3EDI_1C18.Models.Partido>

@{
    ViewBag.Title = "Index";
}

<h2>Copa Mundial de la FIFA Rusia 2018</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.noPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Lab3/Lab3EDI_1C18/Views/Partido/IndexPorFecha.cshtml
@model IEnumerable<Lab3EDI_1C18.Models.Partido>

@{
    ViewBag.Title = "IndexPorFecha";
}

<h2>Copa Mundial de la FIFA Rusia 2018</h2>

@using (Html.BeginForm("Buscar1", "Partido", FormMethod.Get, new { enctype = "multipart/form-data" }))
{
    <h2>Bienvenido a la Copa Mundial de la FIFA Rusia 2018, si desea buscar unicamente por fecha (MMddyyyy) sin poner ninguna separacion</h2>
    @Html.TextBox("id")
    <input type="submit" name="id" value="Buscar Fecha" />
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.noPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>            
            @Html.ActionLink("Delete", "Delete", new { id=item.FechaPartido })
        </td>
    </tr>
}

</table>

Lab3/Lab3EDI_1C18/Views/Partido/IndexPorNumero.cshtml
@model IEnumerable<Lab3EDI_1C18.Models.Partido>

@{
    ViewBag.Title = "IndexPorNumero";
}

<h2>Copa Mundial de la FIFA Rusia 2018</h2>

@using (Html.BeginForm("Buscar", "Partido", FormMethod.Get, new { enctype = "multipart/form-data" }))
{
    <h2>Buscar por el numero del partido</h2>
    @Html.TextBox("id")
    <input type="submit" name="id" value="Buscar Numero" />
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.noPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>