Lab3/Lab3EDI_1C18/Controllers/CargaPartidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab3EDI_1C18.DBContext;
using Lab3EDI_1C18.Models;
using TDA.Clases;
using System.IO;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;

namespace Lab3EDI_1C18.Controllers
{
    public class CargaPartidoController : Controller
    {

       JsonConnection  db = JsonConnection.getInstance;
        // GET: CargaPartido
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Buscar(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaNoPartidoCargados.Find(x => x.noPartido == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        public ActionResult Buscar1(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaFechaPartidoCargados.Find(x => x.FechaPartido.ToString("MMddyyyy") == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }



        public ActionResult IndexInNoPartido()
        {
            return View(db.listaNoPartidoCargados.ToList());
        }

        public ActionResult IndexInFecha()
        {
            return View(db.listaFechaPartidoCargados.ToList());
        }
      
        // GET: CargaPartido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CargaPartido/Create
        public ActionResult Create()
        {
            return View();
        }

        public static int CompararNumero(int actual, int nuevo)
        {
            return actual.CompareTo(nuevo);
        }

        public static int CompararFecha(DateTime actual, DateTime nuevo)
        {
            return actual.CompareTo(nuevo);
        }

        public static int ObtenerNumero(Partido dato)
        {
            return dato.noPartido;
        }

        public static DateTime ObtenerFecha(Partido dato)
        {
            return dato.FechaPartido;
        }

        public static int CompararEnteros(Partido actual, Partido nuevo)
        {
            return actual.noPartido.CompareTo(nuevo.noPartido);
        }


        public static int Compararfecha(Partido actual, Partido nuevo)
        {
            return actual.FechaPartido.CompareTo(nuevo.FechaPartido);
        }

        // POST: CargaPartido/Create
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase postedFile)
        {
           
            db.CargaPartidoFecha.FuncionObtenerLlave = ObtenerFecha;
            db.CargaPartidoFecha.FuncionCompararLlave = CompararFecha;
            db.CargaPartidoNum.FuncionObtenerLlave = ObtenerNumero;
            db.CargaPartidoNum.FuncionCompararLlave = CompararNumero;


            

            if (postedFile != null)
            {
                

                string filepath = string.Empty;
                
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filepath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filepath);

                string csvData = System.IO.File.ReadAllText(filepath);

                db.listaFechaPartidoCargados.Clear();
                db.listaNoPartidoCargados.Clear();

                try
                {
                    JObject json = JObject.Parse(csvData);

                    foreach (JProperty property in json.Properties())
                    {

                        string x = property.Value.ToString();
                        Partido y = JsonConvert.DeserializeObject<Partido>(x);                       
                        db.CargaPartidoNum.Insertar(y);
                        Escribir_archivoNum(y);
                        if (db.CargaPartidoNum.hizoEquilibrio == true)
                        {
                            EscribirEquilibrioNum(y);
                        }         
                            
                        db.CargaPartidoFecha.Insertar(y);
                        Escribir_archivoFecha(y);
                        if (db.CargaPartidoFecha.hizoEquilibrio == true)
                        {
                            EscribirEquilibrioFecha(y);
                        }
                    }
                    db.CargaPartidoFecha.EnOrden(RecorrerPartidoInFecha);
                    db.CargaPartidoNum.EnOrden(RecorrerPartidoInNumero);

                    ViewBag.Message = "Cargado Exitosamente";
             

                }
                catch (Exception )
                {
                    ViewBag.Message = "Dato erroneo.";
                }

            }

            return View();
        }

        public void RecorrerPartidoInFecha(Nodo<Partido> actual)
        {
            db.listaFechaPartidoCargados.Add(actual.valor);
        }

        public void RecorrerPartidoInNumero(Nodo<Partido> actual)
        {
            db.listaNoPartidoCargados.Add(actual.valor);
        }

        public void EscribirEquilibrioNum (Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonNum.txt", sobreescribir);
            sw.WriteLine("Se hizo equilibrio con el partido "+info.noPartido);
            sw.Close();
        }

        public void Escribir_archivoNum (Partido info, bool sobreescribir=true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
               Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonNum.txt",sobreescribir);
            sw.WriteLine("Se inserto el partido NO. " + info.noPartido);
            sw.Close();
        }
        public void Escribir_EliminararchivoNum(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonNum.txt", sobreescribir);
            sw.WriteLine("Se elimino el partido NO. " + info.noPartido);
            sw.Close();
        }

        public void EscribirEquilibrioFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonFecha.txt", sobreescribir);
            sw.WriteLine("Se hizo equilibrio con el partido de fecha " + info.FechaPartido);
            sw.Close();
        }

        public void Escribir_archivoFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonFecha.txt", sobreescribir);
            sw.WriteLine("Se inserto el partido NO. " + info.FechaPartido);
            sw.Close();
        }

        public void Escribir_EliminararchivoFecha(Partido info, bool sobreescribir = true)
        {
            string ruta = Server.MapPath("~/ArchivoLog/");
            if (!Directory.Exists(ruta))
            {
                Directory.CreateDirectory(ruta);
            }
            StreamWriter sw = new StreamWriter(ruta + "\\LogDeArbolJsonFecha.txt", sobreescribir);
            sw.WriteLine("Se elimino el partido NO. " + info.FechaPartido);
            sw.Close();
        }

        // GET: CargaPartido/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CargaPartido/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CargaPartido/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Partido cg = db.listaNoPartidoCargados.Find(x => x.noPartido == id);

            if (cg == null)
            {
                return HttpNotFound();
            }

            return View(cg);
        }

        // POST: CargaPartido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                Partido cg = db.listaNoPartidoCargados.Find(x => x.noPartido == id);
                db.CargaPartidoNum.Eliminar2(cg.noPartido);
                Escribir_EliminararchivoNum(cg);
                if (db.CargaPartidoNum.hizoEquilibrio == true)
                {
                    EscribirEquilibrioNum(cg);
                }

                db.listaNoPartidoCargados.Clear();
                

Lab3/Lab3EDI_1C18/Views/CargaPartido/Buscar.cshtml
@model Lab3EDI_1C18.Models.Partido
@{
    ViewBag.Title = "Buscar";
}

<h2>Buscar el partido de la Copa Mundial de la FIFA Rusia 2018</h2>

<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>
    <br />
            @Html.ActionLink("Back to List", "IndexInNoPartido")
     

Lab3/Lab3EDI_1C18/Views/CargaPartido/Buscar1.cshtml
@model Lab3EDI_1C18.Models.Partido
@{
    ViewBag.Title = "BuscarFecha";
}

<h2>Buscar el partido por fecha de la Copa Mundial de la FIFA Rusia 2018</h2>

<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>
    <br />
    @Html.ActionLink("Back to List", "IndexInFecha")

Lab3/Lab3EDI_1C18/Views/CargaPartido/Create.cshtml
@{
    ViewBag.Title = "Create de Partidos Json";
}

<h2>Carga de Archivo Json para Partidos de la Copa Mundial de la FIFA Rusia 2018</h2>

@using (Html.BeginForm("Create", "CargaPartido", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <span>Seleccionar archivo:</span>
    <input type="file" name="postedFile" />
        <br />
            <input type="submit" value="Subir" />
            <span style="color:green">@ViewBag.Message</span><br />            
}
<br />
<br />
<br />
<div>
    @Html.ActionLink("Mostrar Recorrido En Orden por Fecha", "IndexInFecha")<br />
    @Html.ActionLink("Mostrar Recorrido En Orden por Numero", "IndexInNoPartido")
</div>

Lab3/Lab3EDI_1C18/Views/CargaPartido/Delete.cshtml
@model Lab3EDI_1C18.Models.Partido

@{
    ViewBag.Title = "Eliminar por numero";
}

<h2>Eliminar por numero de partido de la Copa Mundial de la FIFA Rusia 2018</h2>
<pages validaterequest="false"></pages>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexInNoPartido")
        </div>
    }
</div>

Lab3/Lab3EDI_1C18/Views/CargaPartido/Delete1.cshtml
@model Lab3EDI_1C18.Models.Partido

@{
    ViewBag.Title = "Eliminar por fecha";
}

<h2>Eliminar partido por fecha de la Copa Mundial de la FIFA Rusia 2018 </h2>
<pages validaterequest="false"></pages>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.noPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexInFecha")
        </div>
    }
</div>

Lab3/Lab3EDI_1C18/Views/CargaPartido/IndexInFecha.cshtml
@using Lab3EDI_1C18.Models;
@model  IEnumerable<Lab3EDI_1C18.Models.Partido>
@{
    ViewBag.Title = "IndexInFecha";
}
<pages validaterequest="false"></pages>
<h2>Copa Mundial de la FIFA Rusia 2018</h2>

@using (Html.BeginForm("Buscar1", "CargaPartido", FormMethod.Get, new { enctype = "multipart/form-data" }))
{
    <h2>Bienvenido a la Copa Mundial de la FIFA Rusia 2018, si desea buscar unicamente por fecha (MMddyyyy) sin poner ninguna separacion</h2>
    @Html.TextBox("id")
    <input type="submit" name="id" value="Buscar Fecha" />
}

  <table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.noPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estadio)
            </td>
            <td>                

                @Html.ActionLink("Delete", "Delete1", new {  id=(item.FechaPartido.ToString("MMddyyyy")) })
            </td>
        </tr>
    }

</table>

Lab3/Lab3EDI_1C18/Views/CargaPartido/IndexInNoPartido.cshtml
@using Lab3EDI_1C18.Models;
@model  IEnumerable<Lab3EDI_1C18.Models.Partido>

@{
    ViewBag.Title = "IndexInNoPartido";
}

<h2>Ordenar los datos por los numeros de partidos de la Copa Mundial de la FIFA Rusia 2018</h2>
<pages validaterequest="false"></pages>



  @using (Html.BeginForm("Buscar", "CargaPartido", FormMethod.Get, new { enctype = "multipart/form-data" }))
  {
      <h2>Buscar unicamente por numero</h2>
     @Html.TextBox("id") 
      <input type = "submit" name = "id" value = "Buscar Numero"/>
  }


<br />
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.noPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.noPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estadio)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.noPartido })
            </td>
        </tr>
    }

</table>